[project]
name = "chapter02-basic-syntax"
version = "0.1.0"
description = "Chapter 02 - Python Basic Syntax"
readme = "README.md"
requires-python = ">=3.10"
dependencies = []

[tool.uv.workspace]
members = [
    "chapter03-basic-syntax",
]
